version: '3'
services:
  japronto:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: japronto
    container_name: japronto
    ports: 
      - 8080:8080
    tty: true
    volumes:
      - .:/code
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql_japronto
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: japronto
      MYSQL_USER: japronto
      MYSQL_PASSWORD: japronto
      MYSQL_DATABASE: japronto
